In [1]:
import numpy as np

#indexes where the value is 4:
array=np.array([1,2,3,4,5,4,4])
print("Original array:\n",array)

x=np.where(array==4)
print("\nIndexes where the value is 4:\n",x)


Original array:
 [1 2 3 4 5 4 4]

Indexes where the value is 4:
 (array([3, 5, 6]),)


In [2]:
#indexes where the values are even
array=np.array([1,2,3,4,5,6,7,8])
x=np.where(array%2==0)
print("\nOriginal array is:\n",array)
print("\nIndexes where the values are even:\n",x)



Original array is:
 [1 2 3 4 5 6 7 8]

Indexes where the values are even:
 (array([1, 3, 5, 7]),)


In [3]:
#indexes where the value 3 should be inserted, starting from the right x
np.searchsorted(array,3,side='left')
print("\nIndexes where the value 3 should be inserted, starting from the right:",x)



Indexes where the value 3 should be inserted, starting from the right: (array([1, 3, 5, 7]),)


In [5]:
#sorting the array
arr=np.array([3,2,0,1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))



Original array: [3 2 0 1]

Sorted array: [0 1 2 3]


In [7]:
arr=np.array([[3,2,4],[5,0,1]])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))



Original array: [[3 2 4]
 [5 0 1]]

Sorted array: [[2 3 4]
 [0 1 5]]


In [9]:
#filter
arr=np.array([41,42,43,44])
x=[True,False,True,False]
new=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFiltered array:",new)



Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filtered array: [41 43]


In [10]:
arr=np.array([41,42,43,44])
filter=arr>42
new=arr[filter]
print("\nOriginal array:",arr)
print("\nFiltered array condition >42:",filter)
print("\nNew array:",new)


Original array: [41 42 43 44]

Filtered array condition >42: [False False  True  True]

New array: [43 44]
