In [ ]:
import numpy as np
a=np.array([[1,2,4], [5,8,7]])
print("Array created using passed list:\n",a)


Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [ ]:
#creating a 3x4 array with all zeros
b=np.zeros((3,4))
print("\n An array initialised with all zeroes:\n",b)



 An array initialised with all zeroes:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#create a constant value array of complex type
c=np.full((3,3),6)
print("\n An array initialised with all 6s.\n",c)


 An array initialised with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
#create an array with random values
d=np.random.random((2,2))
print("\nA random array:\n",d)


A random array:
 [[0.32262058 0.02727321]
 [0.77322689 0.83711867]]


In [ ]:
#create a sequence of integers from 0 to 30 with steps of 5
e=np.arange(0,30,5)
print("\nA sequential array with steps of 5:\n",e)



A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [ ]:
#reshaping 3x4 array to 2x2x3 array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [2]:
#flatten array
flarr=arr.flatten()
print("\nOriginal array;\n",arr)
print("\nFlattened array;\n",flarr)

NameError: name 'arr' is not defined

In [ ]:
#printing array dimensions
print("\nNo. of dimensions:",arr.ndim)


No. of dimensions: 2


In [ ]:
#printing shape of array
print("\nShape of array: ", arr.shape)


Shape of array:  (3, 4)


In [ ]:
#printing size (total no of elements) of array
print("\nSize of array: ", arr.size)


Size of array:  12


In [ ]:
#printing type of elements in array
print("\nArray stores element of type:", arr.dtype)


Array stores element of type: int64


In [3]:
#coverting datatypes from integer to float
new=arr.astype('f')
print("\nConverted array:\n",new)
print("Converted array type:",new.dtype)

NameError: name 'arr' is not defined