In [7]:
import numpy as np
#an exemplar array
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])

print("Original array:\n",arr)

print("\nEvery other rows:arr[0:3:2]:\n",arr[0:3:2])

#Slicing array
a=arr[:2,:3]
print("\nAn array with first 2 rows and 3 columns:arr[:2,:3]\n",a)

#Integer array indexing example
b=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3), (1,2), (2,1),(3,0):\n",b)

#Boolean array indexing example
c=arr>2
#c is a boolean array
d=arr[c]
print("\nElements greater than 2:\n",d)

#return every other element from the entire array
e=np.array([1,2,3,4,5,6,7])
print("\nOriginal Array:",e)
print("\nReturns every other elements in the array:e[::2]:",e[::2])

#Joining two array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
array=np.concatenate((arr1,arr2))
print("\nOriginal arrays :\n",arr1,arr2)
print("\nJoint array:\n",array)

#horizontal join
horizontal=np.hstack((arr1,arr2))
print("\nHoriozontal joining:\n",horizontal)

#vertical join
vertical=np.vstack((arr1,arr2))
print("\nVertical Joining:\n",vertical)

#depth join
depth=np.dstack((arr1,arr2))
print("\nDepth joining:\n",depth)

#splitting array
arr=np.array([1,2,3,4,5,6])
ab=np.array_split(arr,3)
print("\noriginal array:\n",arr)
print("\nsplitted array:\n",ab)

#display splitted array in another form
print("\nSplitted array in another form:\n")
print(ab[0])
print(ab[1])
print(ab[2])

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

Every other rows:arr[0:3:2]:
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]

An array with first 2 rows and 3 columns:arr[:2,:3]
 [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]

Elements at indices (0,3), (1,2), (2,1),(3,0):
 [4. 6. 0. 3.]

Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]

Original Array: [1 2 3 4 5 6 7]

Returns every other elements in the array:e[::2]: [1 3 5 7]

Original arrays :
 [1 2 3] [4 5 6]

Joint array:
 [1 2 3 4 5 6]

Horiozontal joining:
 [1 2 3 4 5 6]

Vertical Joining:
 [[1 2 3]
 [4 5 6]]

Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]

original array:
 [1 2 3 4 5 6]

splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]

Splitted array in another form:

[1 2]
[3 4]
[5 6]
